# Generated by Django 5.2.4 on 2025-07-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeruser_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
