# Generated by Django 5.2.4 on 2025-07-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeruser_fingerprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='fingerprint',
            new_name='fingerprint_token',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
